# Generated by Django 4.2.16 on 2024-09-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_registration_date_user_created_at"),
    ]

    operations = []
