# Generated by Django 4.2.16 on 2024-09-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
