# Generated by Django 4.2.16 on 2024-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mymodel_my_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(default='2024-09-21T09:58:02.246996+00:00'),
        ),
    ]
