# Generated by Django 5.0.7 on 2024-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mymodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(default='2024-09-21T11:44:51.154682+00:00'),
        ),
    ]
