# Generated by Django 5.0.7 on 2024-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_mymodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(default='2024-09-21T14:47:22.471539+00:00'),
        ),
    ]
