# Generated by Django 5.0.7 on 2024-09-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0021_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_datetime', models.DateTimeField(default=None)),
                ('created_at', models.DateTimeField(default='2024-09-22T11:14:08.191885+00:00')),
            ],
        ),
    ]
