# Generated by Django 5.1.1 on 2024-09-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_remove_fooditems_category_food_items_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food_Items',
            new_name='FoodItem',
        ),
    ]
