# Generated by Django 5.0.7 on 2024-09-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='users',
            field=models.ManyToManyField(blank=True, to='pantry.user'),
        ),
    ]
