# Generated by Django 5.1.1 on 2024-09-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.CharField(blank=True, max_length=1000)),
                ('instructions', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
