# Generated by Django 5.0.7 on 2024-09-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_ingredients_recipe_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
