# Generated by Django 5.1.1 on 2024-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('pantry_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=20)),
                ('ingredient', models.ManyToManyField(to='ingredients.ingredients')),
            ],
        ),
    ]
