# Generated by Django 4.2.16 on 2024-09-23 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pantry", "0005_remove_pantry_users_delete_user_pantry_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pantry",
            name="users",
        ),
        migrations.AddField(
            model_name="pantry",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
