# Generated by Django 5.1.1 on 2024-09-19 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_list',
            fields=[
                ('shopping_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('shopping_list_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_list_item',
            fields=[
                ('shopping_list_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='item', max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('shopping_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shopping_list')),
            ],
        ),
    ]
