# Generated by Django 5.1.1 on 2024-09-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('shopping_list_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.CharField(default='item', max_length=255)),
                ('shopping_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shopping')),
            ],
        ),
    ]
