# Generated by Django 5.1.1 on 2024-09-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='unit_of_measurement',
            field=models.CharField(default='units', max_length=100),
        ),
    ]
