# Generated by Django 5.1.1 on 2024-09-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_shoppingitem_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='unit_of_measurement',
            field=models.CharField(max_length=100),
        ),
    ]
