# Generated by Django 5.1.1 on 2024-09-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_shoppingitem_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='unit_of_measurement',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
