# Generated by Django 5.1.1 on 2024-09-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_shoppinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_list',
            fields=[
                ('shopping_list_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='shopping_list_id',
        ),
        migrations.CreateModel(
            name='Shopping_list_item',
            fields=[
                ('shopping_list_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='item', max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_of_measurement', models.CharField(max_length=100)),
                ('shopping_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shopping_list')),
            ],
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
    ]
