# Generated by Django 5.1.1 on 2024-09-17 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_shopping_list_remove_shoppingitem_shopping_list_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.RenameField(
            model_name='shopping_list_item',
            old_name='item_name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='shopping_list_item',
            old_name='unit_of_measurement',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='shopping_list_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
