# Generated by Django 5.1.1 on 2024-09-19 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_shopping_list_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_list',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
