# Generated by Django 5.1.1 on 2024-09-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_shopping_list_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_list',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
