# Generated by Django 5.1.1 on 2024-09-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_delete_shoppinglist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_list',
            name='date_created',
        ),
    ]
