# Generated by Django 5.1.1 on 2024-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_remove_shopping_list_shopping_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_list_item',
            name='shopping_list_item_id',
        ),
        migrations.AddField(
            model_name='shopping_list_item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
