# Generated by Django 5.1.1 on 2024-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_remove_shopping_list_item_shopping_list_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_list_item',
            name='id',
        ),
        migrations.AddField(
            model_name='shopping_list_item',
            name='shopping_list_item_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
