# Generated by Django 5.1.1 on 2024-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_remove_shopping_list_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_list',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='shopping_list_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
